import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsGithub, BsFacebook, BsLinkedin, BsDiscord } from "react-icons/bs";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.content}>
        <Image
          className={styles.hero}
          src="https://avatars.githubusercontent.com/u/55202082?v=4"
          alt="github profile picture"
          width="150"
          height="150"
        />
        <h1 className={styles.title}>Griffin Ogura</h1>
        <p className={styles.blurb}>Welcome to my humble abode.</p>
        <p className={styles.blurb}>
          Here is a bunch of stuff that I have been doing/building in my free
          time
        </p>
        <ul className={styles.list}>
          <li className={styles.listItem}>
            <Link target="_" href="https://www.linkedin.com/in/gogura/">
              <BsLinkedin />
            </Link>
          </li>
          <li className={styles.listItem}>
            <Link target="_" href="https://github.com/GryphNdor">
              <BsGithub />
            </Link>
          </li>
          <li className={styles.listItem}>
            <Link href="">
              <BsFacebook />
            </Link>
          </li>
          <li className={styles.listItem}>
            <Link href="">
              <BsDiscord />
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
