import Head from "next/head";
import React from "react";
import styles from "../styles/Projects.module.css";

export default function projects() {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Projects</h1>
    </div>
  );
}
